ProjektGrupowy/Controllers/UserPanelController.cs
using ProjektGrupowy.ViewModels;
using System.DirectoryServices;
using System.DirectoryServices.AccountManagement;
using System.Web;
using System.Web.Mvc;

namespace ProjektGrupowy.Controllers
{
    public class UserPanelController : Controller
    {

        [Authorize]
        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (User.IsInRole(Settings.SuperAdminGroupNameLocal))
            {
                Settings.SuperAdminPassword = model.NewPassword;
            }
            else
            {
                var userName = HttpContext.GetOwinContext().Authentication.User.Identity.Name;
                using (PrincipalContext principalContext = Settings.GetPrincipalContext())
                {
                    using (var user = UserPrincipal.FindByIdentity(principalContext, IdentityType.SamAccountName, userName))
                    {
                        user.SetPassword(model.NewPassword);
                    }
                }
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult ChangeData()
        {
            var userName = HttpContext.GetOwinContext().Authentication.User.Identity.Name;
            ChangeDataViewModel model = new ChangeDataViewModel();

            using (PrincipalContext principalContext = Settings.GetPrincipalContext())
            {
                using (var user = UserPrincipal.FindByIdentity(principalContext, IdentityType.SamAccountName, userName))
                {

                    model.Email = user.EmailAddress;
                    model.Name = user.GivenName;
                    model.Surname = user.Surname;
                    DirectoryEntry entry = (DirectoryEntry)user.GetUnderlyingObject();
                    string zgody;
                    if (entry.Properties["postalCode"].Value == null)
                    {
                        zgody = null;
                    }
                    else {
                        zgody = entry.Properties["postalCode"].Value.ToString();
                    }
                    if (!(string.IsNullOrEmpty(zgody)))
                    {
                        if (entry.Properties["postalCode"].Value.ToString().Contains("GIODO") && entry.Properties["postalCode"].Value.ToString().Contains("Newsletter"))
                        {
                            var info = entry.Properties["postalCode"].Value.ToString().Split(';');
                            var giodo = info[0].Split(':');
                            var newsletter = info[1].Split(':');
                            if (giodo[1] == "0")
                            { model.GIODO = false; }
                            else { model.GIODO = true; }
                            if (newsletter[1] == "0")
                            { model.Newsletter = false; }
                            else { model.Newsletter = true; }
                        }
                        else
                        {
                            model.GIODO = false;
                            model.Newsletter = false;

                        }
                    }
                    else
                    {
                        model.GIODO = false;
                        model.Newsletter = false;
                    }

                }
            }
            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeData(ChangeDataViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var userName = HttpContext.GetOwinContext().Authentication.User.Identity.Name;
            using (PrincipalContext principalContext = Settings.GetPrincipalContext())
            {
                using (var user = UserPrincipal.FindByIdentity(principalContext, IdentityType.SamAccountName, userName))
                {
                   
                    user.EmailAddress = model.Email;
                    user.GivenName = model.Name;
                    user.Surname = model.Surname;
                    DirectoryEntry entry = (DirectoryEntry)user.GetUnderlyingObject();
                    string zgody;
                    if (entry.Properties["postalCode"].Value == null)
                    {
                        zgody = null;
                    }
                    else
                    {
                        zgody = entry.Properties["postalCode"].Value.ToString();
                    }
                    if (!(string.IsNullOrEmpty(zgody)))
                    {
                        if (entry.Properties["postalCode"].Value.ToString().Contains("GIODO") && entry.Properties["postalCode"].Value.ToString().Contains("Newsletter"))
                        {
                            var info = entry.Properties["postalCode"].Value.ToString().Split(';');
                            entry.Properties["postalCode"].Value = model.GIODO ? "GIODO:1;" : "GIODO:0;";
                            entry.Properties["postalCode"].Value += model.Newsletter ? "Newsletter:1;" : "Newsletter:0;";
                            if (info.Length > 2)
                            {
                                for (int i = 2; i < info.Length; i++)
                                {
                                    entry.Properties["postalCode"].Value += info[i];
                                }
                            }
                        }
                        else
                        {
                            var info = entry.Properties["postalCode"].Value.ToString();
                            entry.Properties["postalCode"].Value = model.GIODO ? "GIODO:1;" : "GIODO:0;";
                            entry.Properties["postalCode"].Value += model.Newsletter ? "Newsletter:1;" : "Newsletter:0;";
                            entry.Properties["postalCode"].Value += info;
                        }
                    }
                    else
                    {
                        entry.Properties["postalCode"].Value = model.GIODO ? "GIODO:1;" : "GIODO:0;";
                        entry.Properties["postalCode"].Value += model.Newsletter ? "Newsletter:1;" : "Newsletter:0;";
                    }
                    user.Save();
                    entry.CommitChanges();
                }
            }
            return View(model);
        }

    }
}

ProjektGrupowy/Views/Shared/_ErrorMessage.cshtml
@{
    ViewBag.Title = "_ErrorMessage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Head
{
<meta http-equiv="refresh" content="5;@Url.Content("~/")" />
}

<h2>Wystąpił błąd :()</h2>

@ViewBag.ErrorMessage

ProjektGrupowy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @RenderSection("Head", required: false)
    <style>
        #HaveToken:checked + #token {
            display: block !important;
        }
    </style>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/style.less")
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="~/Content/DataTables/datatables.min.js"></script>
</head>
<body>

    <div style="display:table; width: 100%; min-height: 100vh">
        <div class="navbar-container col-md-2 col-sm-2">
            <nav class="navbar-side">
                <div class="col-md-12 ">
                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("Logoff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="account-info">
                                <div class="account-nick">
                                    <p>@User.Identity.Name</p>
                                    <div class="avatar">
                                        <img src="~/images/avatar.png" class="" />
                                    </div>
                                    <a href="javascript:document.getElementById('logoutForm').submit()">Wyloguj się</a>
                                </div>
                            </div>
                        }
                    }
                    else
                    {

                        <div class="account-info">
                            <div class="account-nick">
                                @Html.ActionLink("Zaloguj", "Login", "Account", null, new { id = "loginLink" })
                            </div>
                        </div>


                        <div class="account-nick">

                        </div>
                    }
                    @if (Request.IsAuthenticated)
                    {
                        <div class="links-menu">
                            <div class="main-links">
                                <p>Użytkownik</p>
                                <ul>
                                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "ChangePassword" ? "active" : "")">@Html.ActionLink("Zmien hasło", "ChangePassword", "UserPanel", null, new { @class = "password" })</li>
                                    @if (!(User.IsInRole(Settings.SuperAdminGroupNameLocal)))
                                    {

                                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "ChangeData" ? "active" : "")"> @Html.ActionLink("Zmien dane", "ChangeData", "UserPanel", null, new { @class = "edit" })</li>
                                    }
                                </ul>
                            </div>
                            @if (User.IsInRole(Settings.SuperAdminGroupNameLocal))
                            {
                                <div class="admin-links">
                                    <p>Administrator</p>
                                    <ul>

                                        @if (User.IsInRole(Settings.SuperAdminGroupNameLocal) || User.IsInRole(Settings.ChangeSettingsGroup))
                                        {
                                            <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "ChangeSettings" ? "active" : "")">@Html.ActionLink("Ustawienia", "ChangeSettings", "Home", null, new { @class = "settings" })</li>
                                        }

                                        @if (User.IsInRole(Settings.SuperAdminGroupNameLocal) || User.IsInRole(Settings.SendTokensGroup))
                                        {
                                            <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "TokenGenerate" ? "active" : "")">@Html.ActionLink("Generowanie Tokenów", "TokenGenerate", "Home", null, new { @class = "token" })</li>
                                        }

                                        @if (User.IsInRole(Settings.SuperAdminGroupNameLocal) || User.IsInRole(Settings.EditUsersGroup))
                                        {
                                            <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "UserEditGrid" ? "active" : "")">@Html.ActionLink("Zarządzanie użytkownikami", "UserEditGrid", "Home", null, new { @class = "users" })</li>
                                        }
                                        @if (User.IsInRole(Settings.SuperAdminGroupNameLocal) || User.IsInRole(Settings.EditUsersGroup))
                                        {
                                            <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "ActivateUserFromDataBase" ? "active" : "")">@Html.ActionLink("Aktywacja użytkowników", "ActivateUserFromDataBase", "Home", null, new { @class = "activate" })</li>
                                        }

                                        @if (User.IsInRole(Settings.SuperAdminGroupNameLocal))
                                        {
                                            <li><a href="@Settings.HangfirePath" class="task">Zadania</a></li>

                                        }
                                    </ul>

                                </div>
                            }
                            <div class="back-home">
                                <ul>
                                    <li>
                                        <a href="/">Wróć na stronę główną</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    }
                </div>
            </nav>
        </div>
        <div class="col-md-10 col-sm-10 content-container">
            <div class="body-content" style="margin-top :5%">
                @RenderBody()
                <hr />
                <footer>
                    <div class="container login-footer">

                        <div class="row">
                            <div class="col-md-6">
                            </div>
                            <div class="col-md-6 text-right login-copy">
                                <p>
                                    Copyright 2018 &copy; Rafał Nowak, Patryk Panek, Artur Kisner
                                </p>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </div>



    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ProjektGrupowy/Views/Shared/_NoNavbar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/style.less")
</head>
<body class="login-main">
    <header class="login-header">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h3 class="header-title">@ViewBag.Title</h3>
                </div>
                <div class="col-md-8">
                </div>
            </div>
        </div>
    </header>
    <div class="container login-content">
        @RenderBody()
    </div>
    <footer>
        <div class="container login-footer">
            <hr />
            <div class="row">
                <div class="col-md-6">
                </div>
                <div class="col-md-6 text-right login-copy">
                    <p>
                        Copyright 2018 &copy; Rafał Nowak, Patryk Panek, Artur Kisner
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ProjektGrupowy/Views/Shared/_SuccessMessage.cshtml
@{
    ViewBag.Title = "_SuccessMessage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Head
{
    <meta http-equiv="refresh" content="10;@Url.Content("~/")" />
}

<h2>Zakończono powodzeniem</h2>

@ViewBag.SuccessMessage